### ISSUE TITLE
check for redacted and restricted files with md5 dupes but different filenames

### ISSUE THREAD

**Issue by tcatapano** [cul/lcaaj-metadata#10]

**Comment by tcatapano** [comment]
e.g., happens with filenames with versions ending in "_0AA.tif" and "_AA.tif"

**Comment by tcatapano** [comment]
another example: Three identical files:

- one in "Redacted Images" dir
- another with same filename in "/Columbia_LCAAJ_14-003_Shipment002/LCAAJ_Box094/TIFFS/LCAAJ_94_AnsSheet_48292/"
noted as restricted and redacted based on filename match
- another in
"/Columbia_LCAAJ_14-003_Shipment002/LCAAJ_Box094/TIFFS/LCAAJ_94_AnsSheet_48292/" but with different filename

???

```
34656.
55e72cab3d5981407c0f1126e80b225d
/LCAAJ Redacted Images/LCAAJ_94_AnsSheet_48292_00B.tif
LCAAJ_94_AnsSheet_48292_00B.tif
 
 
72608.
55e72cab3d5981407c0f1126e80b225d
/Columbia_LCAAJ_14-003_Shipment002/LCAAJ_Box094/TIFFS/LCAAJ_94_AnsSheet_48292/LCAAJ_94_AnsSheet_48292_00B.tif
LCAAJ_94_AnsSheet_48292_00B.tif
restricted
redacted
 
 
72751.
55e72cab3d5981407c0f1126e80b225d
/Columbia_LCAAJ_14-003_Shipment002/LCAAJ_Box094/TIFFS/LCAAJ_94_AnsSheet_48292/LCAAJ_94_AnsSheet_48292_221B.tif
 LCAAJ_94_AnsSheet_48292_221B.tif

```

**Comment by dvsokolova** [comment]
All three files in the example are identical. No evidence of redaction was found in the "redacted" version. The text appears to be in Hebrew, so it's unclear whether the document contains any personal information or not and why Box094 has 2 identical files with different filenames.

**Comment by tcatapano** [comment]
see #14
