### ISSUE TITLE
find out paths/names of redacted files

### ISSUE THREAD

**Issue by tcatapano** [cul/lcaaj-metadata#3]
that is, the originals. Do we retain or replace with redacted copies?

**Comment by elohanlon** [comment]
We're going to retain both copies on Isilon, but we'll only ingest redacted copies into Hyacinth (thereby creating Fedora objects for them), and later link the unredacted copy files to those Fedora objects.  So for now, best way to go is to create a spreadsheet that includes these two columns (along with the rest):

- _import_file.import_path
- _import_file.unredacted_copy_import_path

**Comment by elohanlon** [comment]
I spoke with Robbie and Ben about this and we're changing what I said above.  We're not going to link to the unredacted files via Fedora.  They'll be in the Archivematica bag, but won't be referenced by Fedora at all.

New plan: If you and Robbie generate the list of all files that we want to import into Hyacinth (ignoring redactions), and generate a Hyacinth import spreadsheet for those files, I'll find and replace the unredacted version paths with redacted version paths and we'll ingest those into Hyacinth.

Dina and Robbie have identified some problems with the current file set on Isilon, and we need to ask PDCD some questions and delete some likely redundant files and QC spreadsheets, so you'll want to wait before generating a final list of files for import.

**Comment by tcatapano** [comment]
Closed #3.  @rlb179 : perhaps create a note in metadata spreadsheet for ingest into Digital Object Repository (#6 ) to indicate those files which have been redacted?
